[package]
name = "rofi-games"
authors = ["Rolv Apneseth"]
description = "A rofi plugin which adds a mode to list available games for launch along with their box art"
version = "1.1.3"
edition = "2021"
license-file = "LICENSE"

[dependencies]
env_logger = "0.10.0"
log = "0.4.19"
regex = "1.8.1"
rofi-mode = "0.3.0"

[profile.release]
strip = true

[lib]
crate-type = ["cdylib"]
