[package]
name = "rofi-games"
authors = ["Rolv Apneseth"]
description = "A small program which makes a rofi game launcher menu possible by creating .desktop entries for games"
version = "0.0.2"
edition = "2021"
license-file = "LICENSE"

[dependencies]
clap = { version = "4.2.5", features = ["derive", "wrap_help"] }
regex = "1.8.1"

[profile.release]
strip = true
